# postgresql
#   sudo apt-get install postgresql
#   sudo su postgres -c psql
#   alter user postgres password 'apassword';
#   rake db:create
#
development:
    adapter: postgresql
    host: localhost
    username: postgres
    password: apassword
    database: app-dev

test:
    adapter: postgresql
    host: localhost
    username: postgres
    password: apassword
    database: app-test

production:
    adapter: postgresql
    host: localhost
    username: postgres
    password: apassword
    database: app-pro


# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# development:
#   adapter: sqlite3
#   database: db/development.sqlite3
#   pool: 5
#   timeout: 5000
#
# test:
#   adapter: sqlite3
#   database: db/test.sqlite3
#   pool: 5
#   timeout: 5000


# production:
#   adapter: mysql
#   encoding: utf8
#   reconnect: false
#   database: depot_production
#   pool: 5
#   username: gqiao
#   password: q33
#   host: localhost
#   timeout: 5000
